project/main/urls.py
from django.urls import URLPattern, path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('comment/create/<int:blog_id>/', views.comment_create, name='comment_create')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from main import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.first, name='first'),
    path('main/', include('main.urls'))
]

project/main/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Comment(models.Model):
    subject = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment = models.TextField()
    comment_date = models.DateTimeField()

project/main/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Blog, Comment
from django.utils import timezone
# Create your views here.
def main(request):
    blog_list = Blog.objects.all()
    context = {'blog_list' : blog_list}
    return render(request, 'main.html', context)

def first(request):
    return render(request, 'index.html')

def detail(request, blog_id):
    try:
        blog = Blog.objects.get(id=blog_id)
    except Blog.DoesNotExist:
        return render(request, 'blog_error.html')
    else:
        return render(request, 'detail.html', {'blog':blog})

def comment_create(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    blog.comment_set.create(comment = request.POST.get('comment'), comment_date = timezone.now())
    return redirect('main:detail', blog_id = blog.id)

project/main/templates/blog_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h2>게시글을 찾을 수 없습니다.</h2>
</body>
</html>

project/main/templates/detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>{{ blog.subject }}</h1>
    <p>{{ blog.content }}</p>
    <h5>{{ blog.comment_set.count }}개의 댓글이 있습니다.</h5>
    <ul>
        {% for comment in blog.comment_set.all %}
        <li>{{ comment.comment}}</li>
        {% endfor %}
    </ul>
    <form action="{% url 'main:comment_create' blog.id %}" method="POST">
        {% csrf_token %}
        <textarea name="comment" id="comment" rows="10" placeholder="Text..."></textarea>
        <input type="submit" value="등록">
    </form>
    <a href="{% url 'main:main' %}">돌아가기</a>
</body>
</html>

project/main/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <style>
        *{
            color:black;
        }
    </style>
</head>
<body>
    <h1 style="color:black;">ABC</h1>
</body>
</html>

project/main/templates/main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    {% if blog_list%}
    <ul>
        {% for blog in blog_list %}
        <li><a href="{% url 'main:detail' blog.id %}">{{ blog.subject }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <h2>게시글이 없습니다.</h2>
    {% endif %}
</body>
</html>